title: 这是一个嵌入式的示例，咱们可以自定义 # 例如：我的个人博客
description: 网站描述任选 # 例如：分享我的编程经验和生活点滴
author: GIS小队 # 例如：张三

url: "https://USERNAME.github.io"        # 站点主域名，发布前替换USERNAME
baseurl: ""                            # 子路径，若为仓库页面填写 "/仓库名"，否则留空

theme: minima                          # 选用Jekyll官方主题；可根据需要更换
plugins:
  - jekyll-feed                       # RSS/Atom feed 支持
  - jekyll-sitemap                    # 自动生成 sitemap.xml
  - jekyll-seo-tag                    # SEO 元标签支持
  - jekyll-paginate                   # 分页支持

paginate: 5                            # 每页文章数量
paginate_path: "/page/:num/"            # 分页路径格式

markdown: kramdown                     # 使用 kramdown 解析 Markdown
kramdown:
  input: GFM                          # 支持 GitHub Flavored Markdown
  hard_wrap: false                   # 禁用自动换行

permalink: /:categories/:year/:month/:day/:title.html  # 文章固定链接格式

exclude:
  - node_modules
  - vendor
  - Gemfile.lock

# google_analytics: UA-XXXXXXXX-X      # 可选 Google Analytics ID

# 社交链接（可根据需求启用）
social:
  github: "https://github.com/NEGIAO"

# 站点导航（示例）
nav:
  - title: 首页
    url: /
  - title: 博客
    url: /blog/
  - title: 关于
    url: /about/

# 默认值配置
defaults:
  - scope:
      path: ""                     # 对所有文件生效
      type: "posts"
    values:
      layout: "post"               # 文章默认布局
      author: "GIS小队"
